version: '3.1'

services:

  wordpress:
    container_name: $WORDPRESS_CONTAINER_NAME
    depends_on:
      - mysql
    image: wordpress:4.9.8-php7.0
    volumes:
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
  mysql:
    container_name: $MYSQL_CONTAINER_NAME
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
